### ISSUE TITLE
Thrown error by maxRetriesPerRequest is not being caught by the 'error' event handler

### ISSUE THREAD

**Issue by SiNONiMiTY** [redis/ioredis#1776]
I am testing the auto reconnect and command queuing feature of ioredis and I put a simple error event listener that does nothing

```
client.on( 'error', () => { /** EMPTY */ } )
```

Now, after starting the application successfully connecting to the redis instance, I will proceed on shutting down the redis instance.

After a few seconds or so, the app will throw an MaxRetriesPerRequestError and this is not caught by the event handler that I registered. Am I doing anything wrong here?

**Comment by SiNONiMiTY** [comment]
It seems that the event listeners is only for the connection, and I have to handle other errors via the callback of the ioredis methods.

**Comment by SeanDunford** [comment]
@SiNONiMiTY can you share an example of this callback?
