### ISSUE TITLE
"disconnect" does not emit "end" event

### ISSUE THREAD

**Issue by manast** [redis/ioredis#1830]
IORedis version: 5.3.2 (although the same behaviour goes back to at least version 3).

Consider the following code:
```ts
const connection = new IORedis();

connection.on("ready", () => {
  console.log("connection ready");
});

connection.on("error", (error) => {
  console.error(error);
});

connection.on("end", () => {
  console.log("connection ended");
});

console.log("connection disconnecting");
connection.disconnect();
console.log("connection disconnected");
```

The output would be:
```bash
connection disconnecting
connection disconnected
connection ended
```

However, using this code instead:
```ts
const connection = new IORedis();

connection.on("ready", () => {
  console.log("connection ready");
});

connection.on("error", (error) => {
  console.error(error);
});

connection.on("end", () => {
  console.log("connection ended");
});

setTimeout(() => {
  console.log("connection disconnecting");
  connection.disconnect();
  console.log("connection disconnected");
}, 1000);
```

The output would be:

```bash
connection ready
connection disconnecting
connection disconnected
```

In other words, the "end" event is not emitted.

## Why is this important

There are circumstances when you need to know that a connection has indeed been disconnected. For example, say you have a blocking command that is running and you need to close without waiting for said command, then you can issue a call to disconnect, and we would like to know has been disconnected. Furthermore, according to the documentation it should work, and also it works in the first case (because by the time we try to disconnect the connection is not ready yet).

**Comment by trylovetom** [comment]
@luin @manast 

Firstly, I'd like to express my deep admiration for both of your works. The contributions from the [ioredis] @luin and [bullmq] @manast and projects have been invaluable to the community. Truly, both are examples of great work!

Below are the execution results for two pieces of code, one using Node.js (v18.18.2) and the other using Bun (v1.0.7).

Node.js (v18.18.2)
```zsh
% node test1.js
connection disconnecting
connection disconnected
connection ended

% node test2.js
connection ready
connection disconnecting
connection disconnected
connection ended
```

Bun (v1.0.7)
```zsh
% bun test1.js 
connection disconnecting
connection disconnected
connection ended

% bun test2.js
connection ready
connection disconnecting
connection disconnected
```

I was wondering, it seems that ioredis is implemented using the `node:net` module underneath. I suspect that the event emiter of Bun environment might be missing something or its logic differs. Maybe we should report this to the Bun development team?

**Comment by trylovetom** [comment]
@manast Thank you for your reply. I'm eagerly looking forward to bullmq being compatible with Bun officially.

**Comment by manast** [comment]
In this particular case is IORedis that is not compatible with Bun (or Bun incompatible with IORedis)
