### ISSUE TITLE
[Question] Future of ioredis

### ISSUE THREAD

**Issue by gperdomor** [redis/ioredis#1886]
Now that `ioredis` is under Redis organization, a lot of users have questions and a the uncertainty about the future of this project is start to raise

What is the strategy now in short, mid and long term... This project will be deprecated?

**Comment by uglide** [comment]
This question was extensively covered here https://github.com/redis/ioredis/issues/1870#issuecomment-2029351413
Since then, we released [5.4](https://github.com/luin/ioredis/compare/v5.3.2...v5.4.0) maintenance release and executed the strategy outlined before.
