### ISSUE TITLE
Data writing to wrong db after some time

### ISSUE THREAD

**Issue by zaidiqbal** [redis/ioredis#1891]
Hi, 

I have 2 dbs, db0, db1. I use only db0. What happens is that data is correctly entered into db0 and after some time the data starts being writing to db1 without any clear reason. 

I have manually added db: 0, during connection to remove the probability of mistakenly connecting to db1, but still it writes data to db: 1 after some time. 

I am using ioredis version 5.3.1, your help is appreciated, thanks

**Comment by leibale** [comment]
are you using the [`SELECT`](https://redis.io/docs/latest/commands/select/) command at any point (i.e calling `client.select` or `client.call('SELECT')?

**Comment by zaidiqbal** [comment]
no, I just use methods like sadd, smembers etc

**Comment by zaidiqbal** [comment]
> are you using the [`SELECT`](https://redis.io/docs/latest/commands/select/) command at any point (i.e calling `client.select` or `client.call('SELECT')`)?

It was actually this issue, somewhere in the code the select statement was hidden, thanks, it is working fine now.

**Comment by leibale** [comment]
:)
